### ISSUE TITLE
Eternal login message?

### ISSUE THREAD

**Issue by ImLuyou** [ElCholoGamer/userlogin#13]
Seems like for some user (even me), we use to get prompted many times the login request message even when we already did a correctly login.

Steps to replicate: 
- Enter to the server
- Login correctly

Actually this is quite hard to replicate because it does not happen to everybody always

![2021-02-16_16 58 47](https://user-images.githubusercontent.com/15187610/108141330-5fc40380-7078-11eb-9459-788ff1ca11e7.png)

**Comment by ElCholoGamer** [comment]
Hi, I haven't been able to reproduce the issue. Do you have any more information?

**Comment by ImLuyou** [comment]
It's weird, seems to be happening more when the server hasn't been restarted from a while

**Comment by ElCholoGamer** [comment]
Well, I'm pretty sure I fixed the bug. Gonna release v2.10.2 in a bit.
