### ISSUE TITLE
Sent to spawn without registering or loging in

### ISSUE THREAD

**Issue by BennovanDorst** [ElCholoGamer/userlogin#17]
So when a user joins the game when they just started up there game they get sent to the spawn, not to the login/register world where they should spawn.

**Comment by ElCholoGamer** [comment]
What steps can I follow to reproduce this? (Configuration, server software, etc)

**Comment by ElCholoGamer** [comment]
Accidentally pressed close kekw

**Comment by ElCholoGamer** [comment]
Closed for inactivity.
