### ISSUE TITLE
Is this possible? 

### ISSUE THREAD

**Issue by Aadi-mone** [ElCholoGamer/userlogin#19]
This is A simple feature request.

Can you please add a feature like after doing /login password

In the config, we could set command so that we can execute a command like: tp {player} 78 45 321

so this will become a bungee tp login without bungee being installed.

Similar to tp login in bungee

Hope you add it :)

**Comment by ElCholoGamer** [comment]
Hi, if you want to teleport a player after logging in, use `/ul set spawn` to set the coordinates.

**Comment by Aadi-mone** [comment]
oh let me check

**Comment by Aadi-mone** [comment]
ok, that worked but how to change the password of a player?

**Comment by ElCholoGamer** [comment]
You can't change an existing player's password. However, you can use `/ul unregister <player>`, allowing the player to get registered again with a new password.

(By the way, you can ask this kind of stuff on my Discord, it's on the plugin's page. I'm going to close this issue for now.)
