### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by xmyoard** [ElCholoGamer/userlogin#22]
I mean a command that can be executed by the player when the login is completed.

so in the config set-up like this:

commands-after-login

"send hub"
"skript login"
that's all for login commands, now I wanted to say one more feature request.

it's about the hologram.

if you want to see an example there is a server IP: herobrine.org
so there is the other feature request.

hope you like and add it :)

**Comment by ElCholoGamer** [comment]
Will be working on this :)

**Comment by Aadi-mone** [comment]
and also forgot to say the new version is not working on 1.16.5

**Comment by ElCholoGamer** [comment]
> 
> 
> and also forgot to say the new version is not working on 1.16.5

Yes, someone reported this on Discord. Working on it.

**Comment by Aadi-mone** [comment]
nice.

**Comment by ElCholoGamer** [comment]
Feature added! Closing this now.
