### ISSUE TITLE
operator commands are NOT blocked before login

### ISSUE THREAD

**Issue by AGallardoLoya** [ElCholoGamer/userlogin#35]
I was trying out the plugin when i noticed i could join my server and use operator commands before logging in.

This is a problem because a cracked client might use it to join a server using the operator’s username and cause mayhem

I hope this is a problem on my part, and perhaps i have set up the plugin incorrectly, but i can’t be sure.

I tried contacting experienced users through a discord server, as is usual for some projects on github, but i couldn’t find any, so i posted this here.

**Comment by ElCholoGamer** [comment]
Will look into this ASAP 👍 

(For the record, we do have a support server which you can join [here](https://discord.com/invite/gbjaEDzRXU))

**Comment by x13x54** [comment]
Did you change the config file?
> I was trying out the plugin when i noticed i could join my server and use operator commands before logging in.

Because it **will** let you do this if you don't configure it before use.
Toggle all restrictions from false to true to enable the restrictions

**Comment by AGallardoLoya** [comment]
> Did you change the config file?
> 
> > I was trying out the plugin when i noticed i could join my server and use operator commands before logging in.
> 
> Because it **will** let you do this if you don't configure it before use. Toggle all restrictions from false to true to enable the restrictions

I hadn’t i’ve edited the file and rebooted the server, it worked perfectly, many thanks!

**Comment by ElCholoGamer** [comment]
Alr, closing this now
